version: "3.7"

services:
    postgres:
        hostname: postgres
        image: postgres
        environment:
            POSTGRES_PASSWORD: "secret"
            POSTGRES_DB: "league_db"
        ports:
            - "5432:5432"

    league_api:
        hostname: league_api
        build:
            context: ../.
        environment:
            bucket_name: "LOCAL"
            db_user: "postgres"
            db_password: "secret"
            db_endpoint: "postgres"
            db_port: "5432"
            db_name: "league_db"
        ports:
            - "80:80"
        volumes:
            - ../league_api:/app
        depends_on:
            - postgres