# Generated by Django 3.0.3 on 2020-11-08 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('championships_won', models.IntegerField()),
                ('coach', models.CharField(max_length=200)),
                ('number_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=200)),
                ('appearance', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('number_teams', models.IntegerField()),
                ('current_champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_l_t_cc', to='core.Team')),
                ('most_appearances', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Player')),
                ('most_championships', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_l_t_mc', to='core.Team')),
                ('teams', models.ManyToManyField(blank=True, to='core.Team')),
            ],
        ),
    ]
