# Generated by Django 3.0.3 on 2020-11-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='most_appearances',
        ),
        migrations.RemoveField(
            model_name='league',
            name='most_championships',
        ),
        migrations.RemoveField(
            model_name='league',
            name='number_teams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='number_players',
        ),
        migrations.AlterField(
            model_name='player',
            name='appearance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='championships_won',
            field=models.IntegerField(default=0),
        ),
    ]
